name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          unzip

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK minimal (no auto updates)
      env:
        ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      run: |
        set -euxo pipefail
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        cd "$ANDROID_SDK_ROOT"
        curl -sSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q cmdtools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
        # DO NOT run sdkmanager --update (prevents pulling latest 36.x)
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0"
        ls -la "$ANDROID_SDK_ROOT/build-tools" || true
        ls -la "$ANDROID_SDK_ROOT/platforms" || true
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROIDSDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    - name: Pin Buildozer/p4a to API 31 toolchain
      run: |
        sed -i 's/^android\.api = .*/android.api = 31/' buildozer.spec || true
        sed -i 's/^android\.minapi = .*/android.minapi = 21/' buildozer.spec || true
        sed -i 's/^android\.ndk = .*/android.ndk = 25b/' buildozer.spec || true
        # Create local.properties in both project and p4a gradle dirs
        echo "sdk.dir=${{ env.ANDROID_SDK_ROOT }}" > local.properties
        mkdir -p .buildozer/android/platform/android
        echo "sdk.dir=${{ env.ANDROID_SDK_ROOT }}" > .buildozer/android/platform/android/local.properties
        # Environment overrides for Gradle to stop "latest" queries
        echo "org.gradle.jvmargs=-Xmx3g" >> gradle.properties
        echo "android.builder.sdkDownload=false" >> gradle.properties

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        pip install -r requirements.txt

    - name: Build APK (API 31 pinned)
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
        P4A_BOOTSTRAP=gradle
        P4A_ignore_setup_py=1
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LocalLLM-ChatApp-APK
        path: bin/*.apk
        retention-days: 90

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0-${{ github.run_number }}
        name: Local LLM Chat App v1.0-${{ github.run_number }}
        body: |
          ## Local LLM Chat App

          A ChatGPT-like Android application that connects to your local LM Studio server.

          ### Installation
          1. Download the APK file below
          2. Install on your Android device
          3. Configure your LM Studio server URL in the app settings

          ### What's New
          - ChatGPT-like interface
          - Connects to local LM Studio server
          - Material Design UI
          - Configurable settings
          - Conversation history

          ### Setup Instructions
          1. Install LM Studio on your computer and load a model
          2. Start the server in LM Studio (default: http://localhost:1234)
          3. Install this APK on your Android device
          4. Open the app and configure settings with your computer's IP address
          5. Start chatting with your local AI!
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}