name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          unzip

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK with sdkmanager and accept licenses
      run: |
        set -euxo pipefail
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        cd "$ANDROID_SDK_ROOT"
        curl -sSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q cmdtools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --update || true
        # Install only specific, stable packages
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"
        # Verify installation
        ls -la "$ANDROID_SDK_ROOT/build-tools" || true
        ls -la "$ANDROID_SDK_ROOT/platforms" || true
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    - name: Pin Buildozer to local SDK and API 34
      run: |
        sed -i 's/^android\.api = .*/android.api = 34/' buildozer.spec || true
        sed -i 's/^android\.ndk = .*/android.ndk = 25b/' buildozer.spec || true
        sed -i 's/^android\.minapi = .*/android.minapi = 21/' buildozer.spec || true
        echo "sdk.dir=$HOME/android-sdk" > local.properties
        echo "ndk.dir=$HOME/android-sdk/ndk/25.0.8775105" >> local.properties || true

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        pip install -r requirements.txt

    - name: Force p4a/Buildozer env to use pinned SDK only
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
      run: |
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        export ANDROIDSDK="$HOME/android-sdk"
        export ANDROID_HOME="$HOME/android-sdk"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROIDSDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        # Pre-create build-tools dir to satisfy AIDL check path
        mkdir -p "$ANDROID_SDK_ROOT/build-tools/34.0.0"
        # Create dummy local.properties in app dir Buildozer uses
        mkdir -p .buildozer/android/platform/android
        echo "sdk.dir=$HOME/android-sdk" > .buildozer/android/platform/android/local.properties

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LocalLLM-ChatApp-APK
        path: bin/*.apk
        retention-days: 90

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0-${{ github.run_number }}
        name: Local LLM Chat App v1.0-${{ github.run_number }}
        body: |
          ## Local LLM Chat App

          A ChatGPT-like Android application that connects to your local LM Studio server.

          ### Installation
          1. Download the APK file below
          2. Install on your Android device
          3. Configure your LM Studio server URL in the app settings

          ### What's New
          - ChatGPT-like interface
          - Connects to local LM Studio server
          - Material Design UI
          - Configurable settings
          - Conversation history

          ### Setup Instructions
          1. Install LM Studio on your computer and load a model
          2. Start the server in LM Studio (default: http://localhost:1234)
          3. Install this APK on your Android device
          4. Open the app and configure settings with your computer's IP address
          5. Start chatting with your local AI!
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}